name: Swift

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: "5.6"
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
